services:
  # --- NEW FRONTEND SERVICE ---
  frontend:
    build: ./frontend
    ports:
      - "8080:80" # Make the UI available on http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: employees
    ports:
      - "3307:3306" # Using 3307 to avoid conflicts
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mysecretpassword
      - DATABASE_NAME=employees
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data: