# Use the official MySQL 8.0 image
FROM mysql:8.0

# Set default environment variables (can also be overridden in docker-compose)
ENV MYSQL_ROOT_PASSWORD=mysecretpassword
ENV MYSQL_DATABASE=employees
